# Site settings
name: Siyan Wang
title: Siyan Wang
description: a machine learning engineer focused on technology &amp; creativity
url: https://sw-cornell.github.io/
baseurl: ''
email: xw672@cornell.com
cover: https://xuening0322.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://xuening0322.github.io/files/xuening-wang.pdf
social: 
  - title: email
    url: mailto:xw672@cornell.com
  - title: github
    url: https://github.com/xuening0322
  - title: linkedin
    url: https://www.linkedin.com/in/xueningwang
  - title: instagram
    url: https://instagram.com/xuening_0322
  - title: blog
    url: http://xuening.wang/blog

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title
