# Site settings
name: Siyan Wang
title: Siyan Wang
description: A tech-savvy media professional dedicated to transforming information creation and delivery, passionate about leveraging innovation for a more inclusive and interactive society.
url: https://sw-cornell.github.io/
baseurl: ''
email: xw672@cornell.com
cover: https://xuening0322.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://xuening0322.github.io/files/xuening-wang.pdf
social: 
  - title: email
    url: mailto:siyansw@gmail.com
  - title: github
    url: https://github.com/sw-cornell/
  - title: linkedin
    url: https://www.linkedin.com/in/siyan-wang-5251368b/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title
