- name: Co-City
  url: https://sw-cornell.github.io/projects/product-co-city
  code: https://sw-cornell.github.io/projects/product-co-city
  description: A user-centric participatory framework enabling communities to propose, vote on, and monitor public projects through transparent budgeting and design processes.
  image_name: ../img/co-city.jpg
  used:
    - thing: User Research
    - thing: Product Design
    - thing: Social Goods
    - thing: Product Management

- name: Sonorus
  url: https://sw-cornell.github.io/projects/product-sonorus
  code: https://sw-cornell.github.io/projects/product-sonorus
  description: A blockchain-based music platform introducing innovative incentive mechanisms to reward user engagement and promote emerging talent through fair compensation models.
  image_name: ../img/sonorus.jpg
  used:
    - thing: Blockchain Mechanism Design
    - thing: Product Design
    - thing: User Research

- name: Match Day
  url: https://sw-cornell.github.io/projects/product-web-3-hackathon
  code: https://sw-cornell.github.io/projects/product-web-3-hackathon
  description: A Web3 platform that transforms sports viewing into an immersive community experience through blockchain technology, AI-generated NFTs, and interactive fan engagement.
  image_name: ../img/featured/melostream/melostream.png
  used:
    - thing: Product Design
    - thing: Product Management